### ISSUE TITLE
Remove tests for PUT from Conformance Classes

### ISSUE THREAD

**Issue by taniakhalafbeigi** [opengeospatial/sensorthings#10]
Since PUT is an optional functionality in SensorThings, there is no need for testing it in conformance test suite.

**Comment by hylkevds** [comment]
You've closed this issue, but not referenced any commit or pull request, and the "problem" still exists. Did you forget to push any changes?

**Comment by taniakhalafbeigi** [comment]
I opened the issue for the test suite and not the spec in the first place and closed this as of that.
But you are right we need the change it in the spec as well. I will reopen it and thanks for the PR.

**Comment by rhzg** [comment]
I believe, if an implementation of the SensorThings API is implementing a optional feature, it must implement it correctly. Otherwise it shall not be implemented at all. And that should be part of the conformance test. Otherwise optional features run the risk of being implemented in incompatible ways.

**Comment by KathiSchleidt** [comment]
Agreed, either its clearly specified and testable, or it's NOT part of the standard

**Comment by liangsteve** [comment]
Great discussions.  Let's not change the STA specification.  I think any changes to the specification needs to be treated very seriously.  When the SWG designed STA, the text about PUT is really a warning.  It meant to say we SHALL use PUT correctly.  I think we should test it.  Let's keep it the way it is, _i.e._, no change to the specification and the test suite implementation should be enhanced. 

e.g., 
(1) Check PUT supported by a server or not. (e.g., a server SHALL return 501 Not Implemented if PUT is not supported)
(2) If PUT is supported by the server implementation, then it should be implemented correctly.

Hope this is clear.  Thank you all.
