### ISSUE TITLE
PhenomenonTime not updated in Multidatastream obs insertion

### ISSUE THREAD

**Issue by spezzi** [opengeospatial/sensorthings#102]
I'm using both **datastreams** and **multidatastreams** in my FROST installation and I've noticed that **phenomenonTime** is set only for datastreams. 
I've seen the 3 triggers fired in the CRUD operations on OBSERVATIONS table that run the procedures to update phenomenontime, resulttime and observed_area fields in DATASTREAMS table, but no functions for MULTIDATASTREAMS. 

Am I missing something? tnx

**Comment by KathiSchleidt** [comment]
Well - it may be more efficient to put this in on the FROST GitHub as it's an implementation issue, nothing to do with the standard itself

https://github.com/FraunhoferIOSB/FROST-Server/issues

**Comment by spezzi** [comment]
You're completely right! I messed up with too many open browser tabs! Sorry again
