### ISSUE TITLE
Add conformance test for operatore precendence

### ISSUE THREAD

**Issue by taniakhalafbeigi** [opengeospatial/sensorthings#11]
Annex A does not have tests for checking operator precedence. This test can ensure all SensorThings services responses are consistent.
It is also related to #6 .

**Comment by taniakhalafbeigi** [comment]
#6

**Comment by hylkevds** [comment]
A possible wording change is available here:
https://github.com/hylkevds/SensorThingsAPI/commit/933c1faf56f4ca1a3a00ea9a300e61d0045c73f0

**Comment by hylkevds** [comment]
I've reworked my changeRequest repository, new diff available here:
https://github.com/hylkevds/SensorThingsAPI/commit/d3ef864571c7fe4c209a2c8b549ce3cd6e0e82d8?diff=unified

**Comment by hylkevds** [comment]
Fixed with the publication of Sensing v1.1.
