### ISSUE TITLE
Add integrity contraint between Things and HistoricalLocations removal

### ISSUE THREAD

**Issue by albertopq** [opengeospatial/sensorthings#17]
According to the compliance tests [1], it seems that, when deleting a Thing, is expecting all HistoricalLocations related to it to be removed as well. I don't see that constraint in table 25 [2].

[1] https://github.com/opengeospatial/ets-sta10/blob/master/src/main/java/org/opengis/cite/sta10/createUpdateDelete/Capability2Tests.java#L1026
[2] http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#table_25

**Comment by selimnairb** [comment]
@taniakhalafbeigi @hylkevds Here is a PR for this issue: https://github.com/opengeospatial/sensorthings/pull/74

**Comment by hylkevds** [comment]
Thanks for the PR, looks good.

**Comment by hylkevds** [comment]
Fixed with the publication of Sensing v1.1.
