### ISSUE TITLE
22-034r1: Referencing old O&M instead of new OMS

### ISSUE THREAD

**Issue by SpeckiJ** [opengeospatial/sensorthings#191]
When reading the charter document I noticed that the STA SWG struggles with the renaming the same as `Connected Systems SWG` does :) (https://github.com/opengeospatial/ogcapi-connected-systems/issues/69)

Page 5:

    The OGC Observations and Measurements (O&M) v3.0:

It's called Observations, Measurements, and Samples (OMS) now: https://www.ogc.org/standard/om/ -  I also think  `O&M v3.0` never existed as they released 3.0 under the new name already (i am not 100% on that). 

Probably too late to change it now for the running Charter change, but maybe the template should be adapted so it does not get copied over if it is reused.

**Comment by hylkevds** [comment]
True, that was written before O&M was renamed to OMS, and the charter update only adds a task, didn't change anything else.
The tentative timeline for V2 was also slightly too optimistic :D

I've added a commit it so it'll come along with the next update.
