### ISSUE TITLE
Version prefix in MQTT topics

### ISSUE THREAD

**Issue by hylkevds** [opengeospatial/sensorthings#24]
This point was raised in the test suit pull request: https://github.com/opengeospatial/ets-sta10/pull/20

In the HTTP requests, all URLs contain the version prefix (v1.0). The MQTT topics do not contain this prefix. This means the MQTT topics are not "version safe". Was this on purpose, or should we add the version prefix to the MQTT topics as well?

**Comment by hylkevds** [comment]
What do current implementations do?
FROST wants the version prefix.
How about SensorUP and Gost?

**Comment by taniakhalafbeigi** [comment]
We have version prefix like `v1.0/Observations`.

**Comment by bertt** [comment]
In GOST there is no version info in the topic (just like the samples in the spec pdf)

**Comment by hylkevds** [comment]
Fixed with the publication of Sensing v1.1.
