### ISSUE TITLE
Time Interval vs Time

### ISSUE THREAD

**Issue by dpmcgarry** [opengeospatial/sensorthings#35]
Observation phenomenonTime (and a few others) are stated in the spec as intervals but in the ref. impl they are a Time (not an interval). Is it "ok" to have just a timevalue or is interval required?

**Comment by hylkevds** [comment]
On an Observation the phenomenonTime can be either a time, or a time interval:

> TM_Object (ISO 8601 Time string or Time Interval string (e.g., 2010-12-23T10:20:00.00-07:00 or 2010-12-23T10:20:00.00-07:00/2010-12-23T12:20:00.00-07:00))

On a Datastream, the phenomenonTime is a time interval:

> TM_Period (ISO 8601 Time Interval)

**Comment by dpmcgarry** [comment]
Thanks, must have missed that.
