### ISSUE TITLE
Turn off server driven pagination for all entities

### ISSUE THREAD

**Issue by chhonker** [opengeospatial/sensorthings#37]
What values should be set for DEFAULT_TOP and MAX_TOP tags to stop pagination.
Or Is there a way to turn off server driven pagination so that request returns all the data.

**Comment by hylkevds** [comment]
I'm guessing this belongs in https://github.com/FraunhoferIOSB/SensorThingsServer ?
If so: You can not currently turn it off, but you can set it to 2147483647 (the maximum integer value), but why would you want to do that?
