### ISSUE TITLE
Use of Thing.properties to report device status

### ISSUE THREAD

**Issue by HolySamosa** [opengeospatial/sensorthings#63]
I'm trying to identify an appropriate way for a Thing to report current status information, such as battery level.  Battery level is really a 'meta' property of sorts, not core to the domain we are observing so generating Observations does not seem appropriate.  Would this be a valid use case for a device writing to Thing.properties?

Thanks!

**Comment by taniakhalafbeigi** [comment]
To me, even if it is not a core feature, it makes sense to keep a Datastream for battery level and keep the battery status there. It might be of useful in future for example see the trend that the device uses battery or so. Even for other status information if the trend is useful for you, I would suggest to keep a Datastream for it.
But if you prefer to keep it in the Thing properties and only keep the latest status information, you can do that as well.
As you mentioned, Thing.properties is meant for some metadata about the Thing. Deployment condition could be an example for a temperature sensing device, whether it is in shade or not! If something is considered as metadata in your use case you can keep it in "properties".

**Comment by HolySamosa** [comment]
Thanks, Tania.  This is helpful.  We've decided to create a Datastream to report battery level.
