### ISSUE TITLE
Use of undefined operator type cast

### ISSUE THREAD

**Issue by mjacoby** [opengeospatial/sensorthings#8]
This issue has already been submitted as change request and is just posted here to have a central place where all the issues can be found

Section 9.3.3.1 of the standard says:

> A type cast using the qualified entity type name SHALL be ordered by a property defined on a derived type.

but type _cast_ is not defined in SensorThings API. As it is defined in the referenced section of OData I assume this is a copy & paste issue and this sentence was not intended to be part of the SensorThings API standard.

See the original [change request 384](http://ogc.standardstracker.org/show_request.cgi?id=384)

**Comment by hylkevds** [comment]
Fixed with the publication of Sensing v1.1.
